#include "include/Version.hxx"

namespace abxhttpd
{
    ABXHTTPD_INT_GEN(ABXHTTPD_VERSION_MAIN);
    ABXHTTPD_INT_GEN(ABXHTTPD_VERSION_SUB);
    ABXHTTPD_INT_GEN(ABXHTTPD_VERSION_LAST);
    ABXHTTPD_STR_GEN(ABXHTTPD_RELEASE_DATE);
    ABXHTTPD_INT_GEN(ABXHTTPD_VERSION_HEX);
    ABXHTTPD_STR_GEN(ABXHTTPD_VERSION_TEXT);
    ABXHTTPD_STR_GEN(ABXHTTPD_COMPILE_TIME);
}